kind: Service
apiVersion: apps/v1
metadata:
  name: jupyter-notebook
spec:
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30040
    port: 8888
    targetPort: 8888
  selector:
    app: jupyter-notebook
