apiVersion: v1
kind: Service
metadata:
  name: jupyter-notebook
  namespace: jupyter-test
spec:
  type: NodePort
  selector:
    app: jupyter-notebook
  ports:
      # 기본적으로 그리고 편의상 `targetPort` 는 `port` 필드와 동일한 값으로 설정된다.
    - port: 8888
      targetPort: 8888
      # 선택적 필드
      # 기본적으로 그리고 편의상 쿠버네티스 컨트롤 플레인은 포트 범위에서 할당한다(기본값: 30000-32767)
      nodePort: 30040
